#!/bin/bash

apt -y update
apt -y install git default-jdk maven unzip
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install
key_id="?"
key="?"
region="ru-central1"
format="json"
aws configure set aws_access_key_id $key_id
aws configure set aws_secret_access_key $key
aws configure set region $region
aws configure set output $format
cd ~/ && git clone https://github.com/Elferey/my_box.git
cd ./my_box && mvn package
aws --endpoint-url=https://storage.yandexcloud.net/ \
  s3 cp /root/my_box/target/hello-1.0.war s3://elferey/hello-1.0.war

apt install -y docker.io docker-compose
cd ~/ && git clone https://github.com/vegasbrianc/prometheus.git
