#!/bin/bash

apt update
apt install -y tomcat9
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install
key_id="YCAJEus89fiWBHOrnkx-Mun4b"
key="YCMRz-pjdf2X3JgBELUmpkgiEx-pr_8FoAbrpfTe"
region="ru-central1"
format="json"
aws configure set aws_access_key_id $key_id
aws configure set aws_secret_access_key $key
aws configure set region $region
aws configure set output $format
sleep 5m
aws --endpoint-url=https://storage.yandexcloud.net \
  s3 cp s3://elferey/hello-1.0.war /var/lib/tomcat9/webapps
wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
tar -xvzf node_exporter-1.5.0.linux-amd64.tar.gz
cd node-exporter-1.5.0.linux-amd64 && cp node-exporter /usr/local/bin
useradd --no-create-home --shell /bin/false node_exporter
echo "[Unit]\nDescription=Node Exporter\nWants=network-online.target\nAfter=network-online.target\n\n[Service]\nUser=node_exporter\nGroup=node_exporter\nExecStart=/usr/local/bin/node_exporter\n\n[Install]\nWantedBy=default.target" >> /etc/systemd/system/node_exporter.service
systemctl daemon-reload
systemctl start node_exporter.service