#!/bin/bash

apt update
apt install -y tomcat9
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install
key_id="?"
key="?"
region="ru-central1"
format="json"
aws configure set aws_access_key_id $key_id
aws configure set aws_secret_access_key $key
aws configure set region $region
aws configure set output $format
sleep 5m
aws --endpoint-url=https://storage.yandexcloud.net \
  s3 cp s3://elferey/hello-1.0.war /var/lib/tomcat9/webapps